Allow running ni-python-styleguide as a pre-commit hook
ni/python-styleguide pull request #114
Opened 2023-03-15 22:59 UTC by bkeryan

### What does this Pull Request accomplish?

Add a [pre-commit](https://[pre-commit](https://pre-commit.com/).com/) hooks file so that other projects can run `ni-python-styleguide` as a pre-commit hook.

Add a `pre-commit` config file to enable some pre-commit hooks for commits to this repo.

### Why should this Pull Request be merged?

Running `ni-python-styleguide` automatically may save developers time and prevent failed PR builds. 

### What testing has been done?

Tested running `ni-python-styleguide` with `poetry1.2 run pre-commit try-repo C:\dev\python-styleguide ni-python-styleguide --all-files`.
Tested this repo's hooks with `poetry run pre-commit run --all-files`.

2023-03-15 23:11 UTC, bkeryan commented
This test is failing without my change:

```
====================================================== FAILURES =======================================================
________________________________ test_bad_codeblocks_document_lint_errors[D.1.12-Bad1] ________________________________

lint_codeblock = <function lint_codeblock.<locals>.run_linter at 0x000001D5DBA21EE0>
bad_codeblock = <tests.test_convention_doc.doctypes.Codeblock object at 0x000001D5DA59FD30>

    def test_bad_codeblocks_document_lint_errors(lint_codeblock, bad_codeblock):
        """Tests that "bad" codeblocks fail to lint and documents the resulting error codes."""
        if bad_codeblock.rule.is_automatically_enforced:
            result = lint_codeblock(
                bad_codeblock,
                "--format='%(code)s'",
                ignore_unused_imports=("F401" not in bad_codeblock.rule.error_codes),
            )
            assert not result, result.output

            error_codes = set(code.strip("'") for code in result.output.splitlines())
            assert error_codes
            expected_error_codes = set(bad_codeblock.rule.error_codes)
            error_codes_not_expected = error_codes - expected_error_codes
>           assert error_codes.issubset(
                expected_error_codes
            ), f'"Bad" codeblock caused unexpected lint error - {error_codes_not_expected}'
E           AssertionError: "Bad" codeblock caused unexpected lint error - {'BLK100'}
E           assert False
E            +  where False = <built-in method issubset of set object at 0x000001D5DB8E3E40>({'D201', 'D211'})
E            +    where <built-in method issubset of set object at 0x000001D5DB8E3E40> = {'BLK100', 'D201'}.issubset

tests\test_convention_doc\test_codeblocks.py:68: AssertionError
-------------------------------------------------- Captured log call --------------------------------------------------
INFO     flake8:flake8_black.py:63 flake8-black: loading black settings from C:\Dev\python-styleguide\ni_python_styleguide\config.toml
WARNING  flake8.plugins.reporter:reporter.py:35 "'%(code)s'" is an unknown formatter.  Falling back to default.
WARNING  flake8.checker:checker.py:105 The multiprocessing module is not available. Ignoring --jobs arguments.
INFO     flake8.checker:checker.py:264 Making checkers
INFO     flake8.checker:checker.py:175 Checking 1 files
INFO     flake8.main.application:application.py:234 Finished running
INFO     flake8.main.application:application.py:265 Reporting errors
INFO     flake8.main.application:application.py:269 Found a total of 4 violations and reported 2
=============================================== short test summary info ===============================================
FAILED tests/test_convention_doc/test_codeblocks.py::test_bad_codeblocks_document_lint_errors[D.1.12-Bad1] - AssertionError: "Bad" codeblock caused unexpected lint error - {'BLK100'}
============================================ 1 failed, 825 passed in 7.41s ============================================
```

2023-03-16 11:42 UTC, mshafer-NI requested changes

2023-03-16 11:42 UTC, mshafer-NI commented on CONTRIBUTING.md
> +poetry run pre-commit install
I'm guessing this is after "poetry install"?

2023-03-16 11:42 UTC, mshafer-NI commented on README.md
> +    rev: v0.4.1
so when we bump, everyone has to bump??

2023-03-16 11:42 UTC, mshafer-NI commented on .pre-commit-config.yaml
> +        exclude: '^tests/test_cli/acknowledge_existing_errors_test_cases__snapshots/'
the `output*.py` files are expected to comply (see pyproject.toml). Are we not able to make this exclude only the input files?

2023-03-16 11:42 UTC, mshafer-NI commented on .pre-commit-config.yaml
> +    rev: 23.1.0
We've chosen to not pin black and instead let the poetry lock pipeline re-run it to update anything needed. Does pre-commit not support just running whatever is in the lock file?

2023-03-16 11:42 UTC, mshafer-NI commented on .pre-commit-config.yaml
> +    rev: 23.1.0
Also should we use ni-python-styleguide here which also enforces that we match black's formatting?

2023-03-16 12:51 UTC, irwand approved these changes
I don't have additional feedback here. I haven't played with pre-commit hook stuff, but the spirit seems good. Thx!

2023-03-16 13:17 UTC, bkeryan commented on CONTRIBUTING.md
> +poetry run pre-commit install
Yes, I'll update this section to say that.

It creates `.git/hooks/pre-commit` with a reference to the currently active Python interpreter:

```
#!/bin/sh
#!/usr/bin/env bash
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03

# start templated
INSTALL_PYTHON='C:\Users\bkeryan\AppData\Local\pypoetry\Cache\virtualenvs\ni-python-styleguide-CNd04y3w-py3.9\Scripts\python.exe'
ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
# end templated

HERE="$(cd "$(dirname "$0")" && pwd)"
ARGS+=(--hook-dir "$HERE" -- "$@")

if [ -x "$INSTALL_PYTHON" ]; then
    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
elif command -v pre-commit > /dev/null; then
    exec pre-commit "${ARGS[@]}"
else
    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
    exit 1
fi
```

Since this is the Python interpreter for my `ni-python-styleguide` virtualenv, it has `pre-commit` installed.

Using `pipx install pre-commit` and `pre-commit install` (with the pipx-installed version) also works.

2023-03-16 13:28 UTC, mshafer-NI commented on README.md
> +    rev: v0.4.1
Then this should be either "main" or "release@latest" (or something) and we start making a "released" branch to reflect what is latest released for use here. (that is, if "use what's in the venv already" isn't an option).

2023-03-16 13:29 UTC, bkeryan commented on .pre-commit-config.yaml
> +    rev: 23.1.0
It supports defining hooks in the local repo: https://pre-commit.com/#repository-local-hooks

It doesn't use the hook definitions in the tool's repo in that case, so you have to specify a few more fields, but perhaps this is worth it to avoid duplicating the tool's version number.

We can use this to run ni-python-styleguide on itself.

2023-03-16 13:30 UTC, bkeryan commented on .pre-commit-hooks.yaml
> +    args: [lint]
Good idea. We can certainly define multiple hooks.

2023-03-16 13:31 UTC, bkeryan commented
I think it would make sense to run `pre-commit run --all-files` in https://github.com/ni/python-styleguide/blob/main/.github/workflows/PR.yml

2023-03-16 13:43 UTC, bkeryan commented
> > I think it would make sense to run `pre-commit run --all-files` in https://github.com/ni/python-styleguide/blob/main/.github/workflows/PR.yml
> 
> Agree with one caveat..., if it makes changes (formatting), how does the developer get those into their local branch? Would they be able to pull? or would they just see that "it got formatted before submission"?

I was thinking it would be the same workflow as when PR.yml runs `ni-python-styleguide lint` directly: the PR build's checks would fail, sending the developer a failure notification email, and they would have to fix the problem manually (possibly by running `pre-commit run --all-files` or `ni-python-styleguide fix`).

`pre-commit` run has more options that seem relevant: https://[pre-commit](https://pre-commit.com/#pre-commit-run).com/#pre-commit-run
- `--show-diff-on-failure`
- `--from-ref` and `--to-ref` would allow restricting to files modified in the PR's branch, but I don't know if that's what we want.

2023-03-16 15:27 UTC, bkeryan commented on .pre-commit-config.yaml
> +        exclude: '^tests/test_cli/acknowledge_existing_errors_test_cases__snapshots/'
This exclusion was unnecessary because `pyproject.toml` already excludes those files.

2023-03-16 15:28 UTC, bkeryan commented on .pre-commit-hooks.yaml
> +    args: [lint]
Also, `lint` or `fix` should go in `entry` not `args` so that it isn't overridden if the client specifies `args`.

2023-03-16 16:00 UTC, mshafer-NI commented
> > > I think it would make sense to run `pre-commit run --all-files` in https://github.com/ni/python-styleguide/blob/main/.github/workflows/PR.yml
> > 
> > 
> > Agree with one caveat..., if it makes changes (formatting), how does the developer get those into their local branch? Would they be able to pull? or would they just see that "it got formatted before submission"?
> 
> I was thinking it would be the same workflow as when PR.yml runs `ni-python-styleguide lint` directly: the PR build's checks would fail, sending the developer a failure notification email, and they would have to fix the problem manually (possibly by running `pre-commit run --all-files` or `ni-python-styleguide fix`).
> 
> `pre-commit` run has more options that seem relevant: https://pre-commit.com/#pre-commit-run
> 
> * `--show-diff-on-failure`
> * `--from-ref` and `--to-ref` would allow restricting to files modified in the PR's branch, but I don't know if that's what we want.

Hmmm, well this impacts whether we should config pre-commit to run "fix" or just "lint" ...
Other than that - sounds good.

2023-03-16 16:17 UTC, bkeryan commented on .pre-commit-config.yaml
> +    rev: 23.1.0
Using local hooks to run Python packages that are already installed in a virtualenv doesn't work very well and the author of `pre-commit` doesn't recommend or support it: 
https://stackoverflow.com/questions/72888074/how-to-configure-pre-commit-config-yaml-to-work-with-poetry

Also, it won't install Python packages located in the current repository:
https://stackoverflow.com/questions/74329631/pre-commit-additional-dependencies-in-a-local-repository

I can easily get `poetry run pre-commit run --all-files` working, but when I run `git commit`, it uses `pre-commit`'s virtualenv, which doesn't have `ni-python-styleguide` installed. 

Using `language: system` and `entry: poetry run ni-python-styleguide lint` doesn't work around this because AFAIK `poetry run` does not activate a virtualenv if one is already active. 

Setting `virtualenvs.in-project: true` and using `entry: .venv\\Scripts\\ni-python-styleguide fix` fails with `Executable `C:devpython-styleguide.venvScriptspython.exe` not found` and I'm not sure why.

2023-03-16 16:26 UTC, mshafer-NI commented on .pre-commit-config.yaml
> +    rev: 23.1.0
Well that's fun. Is our best option to make a "release" branch and use that for the git reference?

2023-03-16 17:12 UTC, bkeryan commented on README.md
> +    rev: v0.4.1
I'll update `Publish-Package.yml` to create/update another tag pointing to the new release. Is `latest` okay?

If if we have a `latest` tag, do we need a "released" branch?

Do we care about lightweight vs. annotated tags? It looks like `v0.4.0` is lightweight so I assume we don't care.

2023-03-16 17:15 UTC, mshafer-NI commented on README.md
> +    rev: v0.4.1
Like the idea of using a tag.
Wasn't aware there's a difference, I imagine lightweight is fine.

2023-03-16 17:19 UTC, bkeryan commented on .pre-commit-config.yaml
> +    rev: 23.1.0
I think running the previous release of `ni-python-styleguide` will cause problems when the style changes.

The easiest solution for *this* repo is not to run `ni-python-styleguide` from a pre-commit hook. I would like to try using https://github.com/floatingpurr/sync_with_poetry to sync the `black` version.

2023-03-16 17:45 UTC, mshafer-NI commented on .pre-commit-config.yaml
> +    rev: 23.1.0
> I think running the previous release of ni-python-styleguide will cause problems when the style changes.

Actually, since ni-python-styleguide doesn't pin `black`, it could also cause a problem with black moves forwards...

I think using that tool to tie the version to poetry.lock is a good optoin.

2024-04-04 11:58 UTC, mbr0wn commented
FYI I tried running `pre-commit` with `ni-python-styleguide lint` (so it wouldn't allow me to commit stuff where the style guide checker fails) and I think it's a useful tool. Note I didn't try this branch, I just created a `repo: local` version. I wouldn't mind this getting merged in some shape, form or fashion.

2024-04-04 12:02 UTC, mbr0wn commented
Also, if it speeds up things to split the hooks file from the rest, that would be helpful. I'm less interested in developing this tool than in using it.

2024-04-11 14:54 UTC, bkeryan commented
I'm closing this PR because I haven't had time to get back to it.

2024-04-11 14:54 UTC, closed without merging