Ignore F401 for __init__.py files
ni/python-styleguide pull request #173
Opened 2024-04-04 11:50 UTC by mbr0wn

These files routinely import other modules without immediately using them with the intention of making them available to the importing module. Moreover, they are rarely even supposed to be used within the same __init__.py file. Marking all of them 'noqa: F410' is redundant.

2024-04-04 12:07 UTC, mshafer-NI commented
Have you considered declaring the `__all__` list? this creates a reference while also explicitly declaring the API.
(reference https://docs.python.org/3/tutorial/modules.html#importing-from-a-package)

2024-04-04 12:08 UTC, mshafer-NI requested changes

2024-04-04 12:08 UTC, mshafer-NI commented on docs/Coding-Conventions.md
> +> 💻 This rule is enforced by error code F401, except in `__init__.py` files
Have you considered declaring the __all__ list? this creates a reference while also explicitly declaring the API.
(reference https://docs.python.org/3/tutorial/modules.html#importing-from-a-package)

2024-04-04 12:19 UTC, mbr0wn commented on docs/Coding-Conventions.md
> +> 💻 This rule is enforced by error code F401, except in `__init__.py` files
Hey @mshafer-NI ,

I don't understand the connection to this change request. I'm talking about not having to amend files like this: https://github.com/ni/python-styleguide/blob/main/ni_python_styleguide/_utils/__init__.py

If I understand this correctly, `__all__` is for people doing `from x import *` (which they shouldn't do according to our own [style guide](https://ni.github.io/python-styleguide/#O-1-6)). This doesn't apply to existing `__init__.py` files that already import stuff from submodules.

2024-04-09 12:30 UTC, mbr0wn commented on docs/Coding-Conventions.md
> +> 💻 This rule is enforced by error code F401, except in `__init__.py` files
@mshafer-NI thanks for sending those explanations, and also the docs on `__all__`, I learned something along the way. 

After processing it for a few days, I still think this here is the right way to go. Also, having scoured peoples thoughts and opinions I really think that `__all__` should be used when `from X import *` does something undesirable, like export functions we want otherwise not exported, or trigger some action that takes long. It should not be used just so we can disable F401 warnings without having to type `noqa: F401`. The downside of using `__all__` is that you now have to maintain lists of exports when doing other changes, which increases maintenance burden and redundancy in `__init__.py` files.

2024-04-09 12:38 UTC, mshafer-NI commented on docs/Coding-Conventions.md
> +> 💻 This rule is enforced by error code F401, except in `__init__.py` files
Thanks for the response. Two notes:
1. This is a drastic departure from current direction and requires more changes in this PR (this rule becomes an "Avoid" instead of "Do Not", and it needs a lot more examples of when is ok and when is not)
2. We will need buy-in from the rest of the PWG members. I've added this to the agenda for our next meeting on April 17th and will forward you the invite.

2024-04-09 12:39 UTC, mshafer-NI commented on ni_python_styleguide/config.ini
> +    # __init__.py files import other modules routinely with directly using them
```suggestion
    # __init__.py files routinely import other modules without directly using them
```

2024-04-10 15:19 UTC, mbr0wn commented on docs/Coding-Conventions.md
> +> 💻 This rule is enforced by error code F401, except in `__init__.py` files
The suggestion I'm making is extremely narrow (just limited to `__init__.py` files), so we should keep the "Do Not" (but I guess we need to update the title). Everything that was previously done to avoid this error (use `noqa` or duplicate symbol names into `__all__`) is still valid and won't throw errors/warnings. I think this won't break the bank 😄

2024-04-17 14:48 UTC, mbr0wn commented on docs/Coding-Conventions.md
> +> 💻 This rule is enforced by error code F401, except in `__init__.py` files
I updated the language according to our conversation.

2024-04-17 17:07 UTC, irwand approved these changes

2024-04-17 17:08 UTC, irwand commented on docs/Coding-Conventions.md
> +> 💻 This rule is enforced by error code F401, except in `__init__.py` files
Thank you for your patience with this.

2024-05-01 14:07 UTC, mshafer-NI approved these changes

2024-05-02 12:24 UTC, mshafer-NI commented on docs/Coding-Conventions.md
> +from .mysubmodule import spam, eggs # OK even if neither are used in this module
Needs to pass `black`

```suggestion
from .mysubmodule import spam, eggs  # OK even if neither are used in this module
```

2024-05-02 12:28 UTC, merged