Turn on pyflakes linting
ni/python-styleguide pull request #32
Opened 2020-11-05 17:35 UTC by thejcannon

This PR enables certain `pyflakes` checks with related changes.

Note the following checks are still "on" in the tool but not called out in the convention:

## Simple logic errors:

### F601 - MultiValueRepeatedKeyLiteral
```python
{'a': 1, 'a': 2}
```

### F602 - MultiValueRepeatedKeyVariable
```python
a = 1
{a: 1, a: 2}
```

### F631 - AssertTuple ("An assert of a non-empty tuple is always True")
```python
>>> assert (False, )
```

### F633 - InvalidPrintSyntax
```python
>>> print >>sys.stderr, "Hello"
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?
```

### F634 - IfTuple ("Booleanizing a non-empty tuple always is True")
```python
>>> if (False,):
...    print("F")
...
F
```

### F821 - UndefinedName (Just one example, use your imagination)
```python
>>> class foo:
...     foo
...
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<stdin>", line 2, in foo
NameError: name 'foo' is not defined
```

### F822 - UndefinedExport 
```python
__all__ = ["a"]
# But 'a' doesn't exist!
```

### F823 - UndefinedLocal
```python
>>> a = 1
>>> def fun():
...     a
...     a = 2
...     return a
...
>>> fun()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<stdin>", line 2, in fun
UnboundLocalError: local variable 'a' referenced before assignment
```

### F901 - RaiseNotImplemented

('raise NotImplemented' should be 'raise NotImplementedError')

## Syntax Error Checks:

### F404 - LateFutureImport
```python
>>> import os
>>> from __future__ import print_statement
File "<stdin>", line 1
SyntaxError: future feature print_statement is not defined
```

### F406 - ImportStarNotPermitted
```python
>>> def a():
...     from os import *
...
File "<stdin>", line 1
SyntaxError: import * only allowed at module level
```

### F407 - FutureFeatureNotDefined
```python
>>> from __future__ import foobar
File "<stdin>", line 1
SyntaxError: future feature foobar is not defined
```

### F621 - TooManyExpressionsInStarredAssignment
```python
>>> a0, a1, ..., a255, *rest = range(1<<8 + 1)
File "<stdin>", line 1
SyntaxError: too many expressions in star-unpacking assignment
```

### F622 - TwoStarredExpressions
```python
>>> a, *b, *c = range(10)
File "<stdin>", line 1
SyntaxError: two starred expressions in assignment
```

### F701 - BreakOutsideLoop
```python
>>> break
File "<stdin>", line 1
SyntaxError: 'break' outside loop
```

### F702 - ContinueOutsideLoop
```python
>>> continue
File "<stdin>", line 1
SyntaxError: 'continue' not properly in loop
```

### F704 - YieldOutsideFunction
```python
>>> yield 4
File "<stdin>", line 1
SyntaxError: 'yield' outside function
```

### F706 - ReturnOutsideFunction
```python
>>> return
File "<stdin>", line 1
SyntaxError: 'return' outside function
```

### F707 - DefaultExceptNotLast
```python
>>> try:
...     pass
... except:
...     pass
... except ValueError:
...     pass
...
File "<stdin>", line 2
SyntaxError: default 'except:' must be last
```

### F721 - DoctestSyntaxError (no example, use your imagination)

### F831 - DuplicateArgument
```python
>>> def foo(bar, bar): pass
...
File "<stdin>", line 1
SyntaxError: duplicate argument 'bar' in function definition
```

## Syntax Warning Checks

### F632 - IsLiteral
```python
>>> f = 'foo'
>>> f is 'foo'
<stdin>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
True
```

2020-11-05 17:42 UTC, mshafer-NI commented
To the question of calling out these rules in the docs, here's some thoughts:

F406 - ImportStarNotPermitted
 - maybe, it's against the style rules to do a wildcard import anyways... so probably fine to not explicitly doc, but also couldn't hur


F721 - DoctestSyntaxError
 - yay! this is the biggest concern against doctests (maybe add a call out in docs that doctests have valid syntax?? seems like this should be obvious...)

2020-11-05 17:51 UTC, mshafer-NI requested changes

2020-11-05 17:51 UTC, mshafer-NI commented on docs/Coding-Conventions.md
> +However, some checks we enforce don't correspond to conventions here as they either represent specific syntax issues or logic errors, both of which we assume the Python file is free from for the purp
```suggestion
However, some checks we enforce don't correspond to conventions here as they either represent specific syntax issues or logic errors. Both of which we assume the Python file is free from for the purposes of this document.
```

2020-11-05 17:51 UTC, mshafer-NI commented on docs/Coding-Conventions.md
> +E.g. `tempfile` is preferred over `temp_file` or `temporary_file`
is this change intentional?

2020-11-05 17:51 UTC, mshafer-NI commented on tests/test_convention_doc/test_codeblocks.py
> +                "Import definitions that are not used" not in bad_codeblock.rule.header_text
hmmmm... that's definitely a magic string that could break this test if we ever tweak the header... could we key off something in the rule or in the expected error code??

2020-11-05 17:55 UTC, DavidCurtiss approved these changes

2020-11-05 18:16 UTC, rtzoeller commented on docs/Coding-Conventions.md
> +However, some checks we enforce don't correspond to conventions here as they either represent specific syntax issues or logic errors, both of which we assume the Python file is free from for the purp
How about this instead?

```suggestion
However, some checks we enforce don't correspond to conventions here as they either represent specific syntax issues or logic errors. We assume the Python file is free from both for the purposes of this document.
```

2020-11-05 18:17 UTC, rtzoeller approved these changes

2020-11-05 19:05 UTC, thejcannon commented on docs/Coding-Conventions.md
> +E.g. `tempfile` is preferred over `temp_file` or `temporary_file`
Yes, the fact that they were codeblocks wasn't adding anything.

2020-11-05 19:19 UTC, thejcannon commented on tests/test_convention_doc/test_codeblocks.py
> +                "Import definitions that are not used" not in bad_codeblock.rule.header_text
Ha! I feel so dumb. Switched it to look for `F401` 😄

2020-11-05 19:22 UTC, mshafer-NI approved these changes

2020-11-05 21:25 UTC, rick-morrow approved these changes

2020-11-05 23:02 UTC, kcuzner approved these changes

2020-11-05 23:41 UTC, irwand approved these changes

2020-11-06 21:08 UTC, sbethur approved these changes

2020-11-12 14:29 UTC, jryckman approved these changes

2020-11-12 15:20 UTC, neilvana approved these changes

2020-11-12 15:31 UTC, pakdev commented on tests/test_convention_doc/test_codeblocks.py
> +            # Undefined named. Defining all the names in each example would detract from the
Undefined name. (remove d)

2020-11-12 15:41 UTC, pakdev commented on docs/Coding-Conventions.md
Apparently GitHub doesn't allow you to comment on lines a short distance away from changed lines, but I think "underscores are permissible, but should be avoided" is a bit harsh. The guidance on the pep-0008 page states "Function[/variable] names should be lowercase, with _words separated by underscores as necessary to improve readability._" That doesn't sound like "avoided" to me, rather, used judiciously.

2020-11-12 15:41 UTC, pakdev commented on docs/Coding-Conventions.md
Apparently GitHub doesn't allow you to comment on lines more than a short distance away from changed lines, but I think "underscores are permissible, but should be avoided" is a bit harsh. The guidance on the pep-0008 page states "Function[/variable] names should be lowercase, with _words separated by underscores as necessary to improve readability._" That doesn't sound like "avoided" to me, rather, used judiciously.

2020-11-12 15:49 UTC, pakdev approved these changes

2020-11-12 15:54 UTC, kcuzner commented on docs/Coding-Conventions.md
Isn't this just referring to package/module names?

2020-11-12 16:08 UTC, alexweav approved these changes

2020-11-12 16:13 UTC, thejcannon commented on docs/Coding-Conventions.md
Yeah this convention is especially about naming packages/modules.
It comes from https://www.python.org/dev/peps/pep-0008/#package-and-module-names
> Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability. Python packages should also have short, all-lowercase names, although the use of underscores is discouraged.

2020-11-12 20:45 UTC, pakdev commented on docs/Coding-Conventions.md
Doh; the example looked like a variable - nm

2020-11-12 21:16 UTC, thejcannon commented on docs/Coding-Conventions.md
Yeah, it was wrong of me to use code blocks previously 😄

2020-11-12 23:02 UTC, alejandro5042 approved these changes

2020-11-18 15:35 UTC, stick152 approved these changes

2020-11-18 16:33 UTC, nethrasuresh approved these changes

2020-11-18 20:27 UTC, merged